language: python
python:
  - "2.7"
  #- "3.3"
cache: pip
install:
  - pip install .
  - cd; python -c "import surfinBH; surfinBH.DownloadData()"; cd -
script:
  - py.test
addons:
  ssh_known_hosts:
      - bitbucket.org
