language: python
python:
  - "2.7"
  - "3.3"
cache: pip
before_install:
  - sudo apt-get install -y wget
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - py.test
addons:
  apt:
    update: true
  ssh_known_hosts:
      - bitbucket.org
